[2023-12-18T15:01:21.587+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: green_taxis_01_2015_pipeline.dashboards_task manual__2023-12-18T15:01:17.321539+00:00 [queued]>
[2023-12-18T15:01:21.591+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: green_taxis_01_2015_pipeline.dashboards_task manual__2023-12-18T15:01:17.321539+00:00 [queued]>
[2023-12-18T15:01:21.591+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-18T15:01:21.597+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): dashboards_task> on 2023-12-18 15:01:17.321539+00:00
[2023-12-18T15:01:21.600+0000] {standard_task_runner.py:57} INFO - Started process 354 to run task
[2023-12-18T15:01:21.603+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'green_taxis_01_2015_pipeline', 'dashboards_task', 'manual__2023-12-18T15:01:17.321539+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmppkuo4ney']
[2023-12-18T15:01:21.604+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask dashboards_task
[2023-12-18T15:01:21.627+0000] {task_command.py:416} INFO - Running <TaskInstance: green_taxis_01_2015_pipeline.dashboards_task manual__2023-12-18T15:01:17.321539+00:00 [running]> on host 02c86e8d4ef1
[2023-12-18T15:01:21.664+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='green_taxis_01_2015_pipeline' AIRFLOW_CTX_TASK_ID='dashboards_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-18T15:01:17.321539+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-18T15:01:17.321539+00:00'
[2023-12-18T15:01:22.565+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dashboards.py", line 21, in initialize_dashboards
    fare_amount_by_payment_type = nyc_df.groupby('payment type')['fare amount'].mean()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 8252, in groupby
    return DataFrameGroupBy(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 931, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/groupby/grouper.py", line 985, in get_grouper
    raise KeyError(gpr)
KeyError: 'payment type'
[2023-12-18T15:01:22.573+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=green_taxis_01_2015_pipeline, task_id=dashboards_task, execution_date=20231218T150117, start_date=20231218T150121, end_date=20231218T150122
[2023-12-18T15:01:22.580+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task dashboards_task ('payment type'; 354)
[2023-12-18T15:01:22.594+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-18T15:01:22.606+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
